# -*- coding: utf-8 -*-
"""Object Detection with YOLOV8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BuGC1CVhlO20FfAo5FGqYaYXfomqZC9d
"""

!pip install ultralytics

from ultralytics import YOLO
import cv2
from google.colab.patches import cv2_imshow
import os
print(os.listdir())

model = ('yolov8n.pt')

from ultralytics import YOLO

# Load the pre-trained YOLO model
model = YOLO("yolov8n.pt")  # or your custom model path

# Run prediction on an image
results = model("sample2.jpg")

# Save the results
results[0].save("output-img.jpg")

from ultralytics import YOLO

# Load the pre-trained YOLO model
model = YOLO("yolov8n.pt")  # or your custom model path

# Run prediction on an image
results = model("one.jpg")

# Save the results
results[0].save("output2-img.jpg")

from ultralytics import YOLO
import os

video_path = "/content/sample-video.mp4 (1).mp4"  # <<< correct your file name here

# Check if video exists
if not os.path.exists(video_path):
    raise FileNotFoundError(f"Video not found: {video_path}")

# Load YOLO model
model = YOLO("yolov8n.pt")

# Run prediction on video and save output automatically
model.predict(
    source=video_path,
    save=True,
    project="runs",
    name="video_output",
    save_frames=False
)